<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>v</string>
    </array>
    <!-- <key>foldingStartMarker</key>
         <string>(?x:       # turn on extended mode
         ^        # a line beginning with
         \s*      # some optional space
         [{\[]    # the start of an object or array
         (?!      # but not followed by
         .*     # whatever
         [}\]]  # and the close of an object or array
         ,?     # an optional comma
         \s*    # some optional space
         $      # at the end of the line
         )
         |        # ...or...
         [{\[]    # the start of an object or array
         \s*      # some optional space
         $        # at the end of the line
         )</string>
         <key>foldingStopMarker</key>
         <string>(?x:     # turn on extended mode
         ^      # a line beginning with
         \s*    # some optional space
         [}\]]  # and the close of an object or array
         )</string> -->
    <key>name</key>
    <string>Coq</string>
    <key>patterns</key>
    <array>

      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\(\*(?!#)</string>
        <key>end</key>
        <string>\*\)</string>
        <key>name</key>
        <string>comment.block.coq</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_double_quoted_string</string>
          </dict>
        </array>
      </dict>

      <dict>
        <key>match</key>
        <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
        <key>name</key>
        <string>constant.numeric.gallina</string>
      </dict>

      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.coq</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.coq</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.coq</string>
      </dict>

    </array>

    <key>repository</key>
    <dict>
      <key>block_comment</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\(\*(?!#)</string>
        <key>end</key>
        <string>\*\)</string>
        <key>name</key>
        <string>comment.block.coq</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_double_quoted_string</string>
          </dict>
        </array>
      </dict>

      <key>block_double_quoted_string</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.coq</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.coq</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.coq</string>
      </dict>

    </dict>

    <key>scopeName</key>
    <string>source.coq</string>
    <key>uuid</key>
    <string>CDE1AD3A-C094-457D-B321-93009C6BCFDA</string>
  </dict>
</plist>
