name: Github CI

on:
  push:
    branches:
      - main
      - v9.2
      - v9.1
      - v9.0
      - v8.20
      - v8.19
      - v8.18
      - v8.17
      - v8.16
      - v8.15
  pull_request:
    branches:
      - main
      - v9.2
      - v9.1
      - v9.0
      - v8.20
      - v8.19
      - v8.18
      - v8.17
      - v8.16
      - v8.15

# Cancels previous runs of the same workflow
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ❄️ Setup Nix
        uses: cachix/install-nix-action@v31
      - name: 📐 Run flake check
        run: |
          set -o pipefail
          # Run flake check, capture failed drv
          nix flake check --show-trace --no-substitute || \
          nix log $(nix eval --raw .#checks.x86_64-linux.treefmt)
